require "rosxnb.launch"
require "rosxnb.options"
require "rosxnb.keymaps"
require "rosxnb.autocommands"

spec "rosxnb.colorscheme"
spec "rosxnb.devicons"
spec "rosxnb.treesitter"
spec "rosxnb.mason"
spec "rosxnb.none_ls"
spec "rosxnb.schemastore"
spec "rosxnb.lspconfig"
spec "rosxnb.cmp"
spec "rosxnb.telescope"
spec "rosxnb.nvimtree"
spec "rosxnb.lualine"
spec "rosxnb.navic"
spec "rosxnb.breadcrumbs"
spec "rosxnb.autopairs"
spec "rosxnb.comment"
spec "rosxnb.indent"

spec "rosxnb.alpha"
spec "rosxnb.maximizer"

require "rosxnb.lazy"
